
wyf:
  security:
#    browser:
#      login-page: /view/demo-login.html
    code:
      image:
        length: 4
        width: 100
        url: /user,/user/*
security:
  oauth2:
    client:
      client-id: my
      client-secret: my-secret